version: "3.7"
services:
    database:
        image: postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
    cache:
        image: bitnami/redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"
        volumes:
            - cache-data:/bitnami/redis/data
    lavalink:
        image: fredboat/lavalink:dev
        ports:
            - "2333:2333"
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
    bot:
        image: node:16
        command: bash -c "npm run dev || (npm install && npm run dev)"
        depends_on:
            - database
            - cache
            - lavalink
        environment:
            - USING_COMPOSE=true
        env_file:
            - .env
        volumes:
            - ./:/home/node/cubot
        working_dir: /home/node/cubot
volumes:
    database-data:
    cache-data:
